### ISSUE TITLE
Trello login broken

### ISSUE THREAD

**Issue by TamaHobbit** [ErikSchierboom/CustomOAuthClient#2]
Clicking on "Login with Trello" throws a DotNetOpenAuth.Messaging.ProtocolException "Error occurred while sending a direct message or getting the response."

[Stacktrace](http://paste.debian.net/914475/)

**Comment by TamaHobbit** [comment]
Woops! I had forgotten to put in the consumerKey and consumerSecret in AuthConfig.cs

Now I'm getting a "Login failure" even though the logs generated with [these instructions](https://github.com/DotNetOpenAuth/DotNetOpenAuth/wiki/Logging-and-debugging) don't show any problem. I don't know if that's a bug in this client or elsewhere.

**Comment by TamaHobbit** [comment]
Fixed; [here's a pullrequest](https://github.com/ErikSchierboom/CustomOAuthClient/pull/3). Exceptions would silently result in login failure

**Comment by ErikSchierboom** [comment]
Great find! I've just merged the pull request. Thanks for helping!
